services:
  warp-proxy:
    image: qmcgaw/gluetun
    container_name: warp_bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "127.0.0.1:${PROXY_PORT:-8888}:8888/tcp"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=162.159.192.1
      - VPN_ENDPOINT_PORT=2408
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY:-bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - HTTPPROXY=on
      - HTTPPROXY_PORT=8888
      - SHADOWSOCKS=off
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - UPDATER_PERIOD=0
    restart: "no"
